version: "3"

tasks:
  check-talos-node:
    dir: ./terraform
    cmds:
      - terraform init
      - terraform plan
  setup-talos-node:
    dir: ./terraform
    cmds:
      - terraform init
      - terraform apply -auto-approve
  gen-talos-config:
    env:
      TALOSCONFIG: "_out/talosconfig"
      CONTROL_PLANE_IP: 192.168.1.57
      WORKER_IP: 192.168.1.133
      TALOS_VERSION: v1.11.1
      SCHEMA: b1ba84be4f5193a24085cc7e22fce31105e1583504d7d5aef494318f7cb1abd0
    cmds:
      - talosctl gen config talos-proxmox-cluster https://$CONTROL_PLANE_IP:6443 --output-dir _out --install-image factory.talos.dev/installer/$SCHEMA:$TALOS_VERSION
      - talosctl --talosconfig $TALOSCONFIG apply-config --insecure --nodes $CONTROL_PLANE_IP --file _out/controlplane.yaml
      - talosctl --talosconfig $TALOSCONFIG apply-config --insecure --nodes $WORKER_IP --file _out/worker.yaml
      - talosctl --talosconfig $TALOSCONFIG config endpoint $CONTROL_PLANE_IP
      - talosctl --talosconfig $TALOSCONFIG config node $CONTROL_PLANE_IP
      - talosctl --talosconfig $TALOSCONFIG config info
  bootstrap-talos:
    desc: This will bootstrap the talos cluster. Make sure to have healthy nodes before running this command.
    env:
      TALOSCONFIG: "_out/talosconfig"
    cmds:
      - talosctl --talosconfig $TALOSCONFIG bootstrap
  add-talos-kubeinfo:
    desc: This will backup your old kubeconfig that lives in the `~/.kube/config` to the `~/.kube/config.bak`
    env:
      TALOSCONFIG: "_out/talosconfig"
    cmds:
      - talosctl --talosconfig $TALOSCONFIG kubeconfig ~/.kube/talos-kubeconfig.yml
  setup-argocd:
    desc: This is to install argocd in the kubernetes cluster.
    summary: See https://argo-cd.readthedocs.io/en/stable/getting_started. The server is accessible in the $PORT and Password available on the `pass` file
    cmds:
      - |
        kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        kubectl patch svc argocd-server -n argocd -p '{"spec": {"type": "ClusterIP"}}'
  get-argocd-password:
    desc: This will get the password for the argocd. Need to wait until the argocd server is active
    cmds:
      - kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 --decode
  port-forward-argocd:
    desc: This will port forward the argocd server to the local machine. Access it through the 8080
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443
