apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: vault-secrets-operator
    targetRevision: "1.0.1"
    helm:
      releaseName: vault-secrets-operator
      values: |
        controller:
          image:
            repository: hashicorp/vault-secrets-operator
            tag: "1.0.1"
        vault:
          address: "http://vault.vault.svc.cluster.local:8200"
        serviceAccount:
          create: true
          name: vault-secrets-operator
        rbac:
          create: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
