apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: citadel-vault-connection
  namespace: vault-secrets-operator
spec:
  address: "http://vault.vault.svc.cluster.local:8200"
  auth:
    method: kubernetes
    mount: kubernetes
    kubernetes:
      role: vault-secrets-operator
      serviceAccount: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: citadel-kubernetes-auth
  namespace: vault-secrets-operator
spec:
  vaultConnectionRef: citadel-vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: vault-secrets-operator
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: citadel-vault-secrets-operator-config
  namespace: vault-secrets-operator
spec:
  type: kv-v2
  path: secrets
  mount: kv
  destination:
    name: citadel-vault-secrets
    create: true
  vaultAuthRef: citadel-kubernetes-auth
