apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: vault-secrets-operator
    targetRevision: "1.0.1"
    helm:
      releaseName: vault-secrets-operator
      valuesFile:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault-secrets-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
