# argocd/apps/couchdb/cors-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-couchdb
  namespace: couchdb
data:
  inifile: |
    [httpd]
    enable_cors = true

    [chttpd]
    enable_cors = true

    [cors]
    origins = *
    credentials = true
    headers = accept, authorization, content-type, origin, referer, x-csrf-token
    methods = GET, PUT, POST, HEAD, DELETE, OPTIONS
