apiVersion: v1
kind: Service
metadata:
  name: couchdb-couchdb
  namespace: couchdb
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: couchdb
    app.kubernetes.io/name: couchdb
    app.kubernetes.io/component: couchdb
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
      nodePort: 30010
