name: Infrastructure change
description: Plan and track an infrastructure change
labels: [infra]
body:
  - type: textarea
    id: motivation
    attributes: { label: Motivation, description: Why is this change needed? }
    validations: { required: true }
  - type: checkboxes
    id: components
    attributes:
      label: Components
      options:
        - label: Terraform
        - label: ArgoCD / Kustomize
        - label: Kubernetes Manifests
        - label: Talos
        - label: Vault / VSO
        - label: Storage (Longhorn / MinIO)
        - label: Networking (Cloudflared / Tailscale)
  - type: textarea
    id: rollout
    attributes: { label: Rollout plan }
  - type: textarea
    id: validation
    attributes: { label: Validation (attach `terraform plan`, `kubectl diff`, links) }
  - type: textarea
    id: backout
    attributes: { label: Backout plan }

