apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: "https://charts.min.io/"
    chart: minio
    targetRevision: "5.4.0"
    helm:
      releaseName: minio
      values: |
        mode: standalone
        rootUser: ""
        rootPassword: ""
        replicas: 2
        pools: 1
        drivesPerNode: 1
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 10Gi
        service:
          type: ClusterIP
          port: 9000
        resources:
          requests:
            memory: "512Mi"
        # Explicitly disable additional storage
        console:
          enabled: false
        # Ensure only data PVCs are created
        defaultBuckets: ""
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
