mode: distributed
rootUser: ""
rootPassword: ""
replicas: 2
persistence:
  enabled: true
  storageClass: "longhorn"
  size: 10Gi
service:
  type: ClusterIP
  port: 9000
resources:
  requests:
    memory: "512Mi"
