apiVersion: v1
kind: namespace
metadata:
  name: infra

---
apiVersion: v1
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: AppProject
    metadata:
      creationTimestamp: "2025-09-14T09:21:56Z"
      generation: 1
      name: infra
      namespace: infra
    spec:
      clusterResourceWhitelist:
        - group: "*"
          kind: "*"
      destinations:
        - namespace: "!kube-system"
          server: "*"
        - namespace: "*"
          server: "*"
      sourceRepos:
        - "*"
kind: List
metadata:
  resourceVersion: ""
